#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleBase64-import-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleBase64-import.h
)

set( PUBLIC_HEADERS
src/MulleBase64.h
src/MulleObjCLoader+MulleBase64.h
src/NSData+Base64.h
src/base64.h
src/import.h
)

