#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleBase64.m
src/NSData+Base64.m
src/base64.c
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleBase64.m
)
